[theme]
primaryColor = "#1e3c72"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"
font = "sans serif"

[server]
# Configurações importantes para produção
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true

[browser]
# Desabilitar coleta de estatísticas em produção
gatherUsageStats = false

[runner]
# Configurações de performance
magicEnabled = true

[client]
# Configurações do cliente
showErrorDetails = false 